const paragraphs = [
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
    "If you donot go after what you want, you will never have it. If you donot ask, the answer is always no. If you donot step forward, you are always in the same place.",
    "The only thing keeping you from getting what you want is the story you keep telling yourself about why you don't have it. People who are willing to die to succeed will tend to succeed. ",
    "People are like stained-glass windows. They sparkle and shine when the sun is out, but when the darkness sets in their true beauty is revealed only if there is light from within.",
    "Nothing splendid has ever been achieved except by those who dared believe that something inside of them was superior to circumstance.",
    "The secret is in not giving up, of all the greats they didn't quit. If you quit I guarantee you're gonna fail, but you don't know what's gunna happen if you don't give in.",
    "Just decide; what's it's gonna be, who you're gonna be and how your gonna do it, and then from that point, the universe will get out of your way.",
    "I have learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.",
    "Take up one idea. Make that one idea your life--think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "When I'm on that field, I give it everything I have, and when I come off, I'm a mom. As tired and exhausting as it is, it's about coming back, even after double days, and still being able to enjoy the kids.",
    "If you want happiness for an hour take a nap. If you want happiness for a day, go fishing. If you want happiness for a year, inherit a fortune. If you want happiness for a lifetime, help someone else",
    "One of the most important things for any leader is to never let anyone else define who you are. And you define who you are. I never think of myself as being a woman CEO of this company. I think of myself as a steward of a great institution.",
    "If you're ever if you're ever thinking, Oh, but I'm a waste of space and I'm a burden, remember: that also describes the Grand Canyon. Why don't you have friends and family take pictures of you from a safe distance? Revel in your majestic profile?",
    "With extreme wealth comes extreme responsibility. And the responsibility for me is to invest in creating new businesses, create jobs, employ people, and to put money aside to tackle issues where we can make a difference.",
    "It's irreverence, foolish confidence, and naivety combined with persistence, open mindedness, and a continual ability to learn that created Facebook, Google, Yahoo, eBay, Microsoft, Apple, Juniper, AOL, Sun Microsystems, and others.",
    "I think people waste so much time strategizing about what they should do, rather than just going and doing something, making mistakes, and then pivoting. The goal of a startup should be: Launch as many things as possible, fail as quickly as possible, and then figure out how to move forward from there.",
    "My biggest influence was realizing the tradeoff my parents made in immigrating to the United States. While neither of them pursued a career in entrepreneurship per se, the risk/reward profile they took was seared in my brain",
];